spring:
  application:
    name: community

  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 파일 최대 크기
      max-request-size: 10MB  # 요청 최대 크기

logging:
  level:
    org.hibernate.SQL: debug